### ISSUE TITLE
BearingFluidFlow error in example 7

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#764]
The example has this error:
![image](https://user-images.githubusercontent.com/18506378/108502131-126eae80-7291-11eb-9d63-4041a9908365.png)

We need to update to the new command (`BearingFluidFlow`).

**Comment by rodrigomoliveira1** [comment]
While fixing it, this example raised another error:

```python
Traceback (most recent call last):

  File "D:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'y_pos_sup'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-8-ce6f152171ec>", line 42, in <module>
    rotor596c.plot_rotor().show(renderer="browser")

  File "D:\Anaconda3\lib\site-packages\ross\rotor_assembly.py", line 2009, in plot_rotor
    Q_(self.df[self.df.tag == bearing.tag]["y_pos_sup"].values[0], "m")

  File "D:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)

  File "D:\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err

KeyError: 'y_pos_sup'
```
